name: WQ
channels:
  - pyg
  - pytorch
  - nvidia/label/cuda-11.8.0
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.8.4=py310h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.15=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pyg=2.5.2=py310_torch_2.1.0_cu118
  - pyqt=5.15.10=py310h6a678d5_0
  - python=3.10.13=h955ad1f_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.1.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=2.1.0=py310
  - typing_extensions=4.11.0=py310h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - wget=1.21.4=h251f7ec_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.10
    - argparse==1.4.0
    - async-timeout==5.0.1
    - attrs==23.2.0
    - automat==22.10.0
    - axial-positional-embedding==0.2.1
    - bottleneck==1.3.7
    - brotli==1.0.9
    - buildtools==1.0.6
    - causal-conv1d==1.2.0.post2
    - certifi==2025.1.31
    - colt5-attention==0.10.20
    - constantly==23.10.4
    - contourpy==1.2.0
    - docopt==0.6.2
    - einops==0.8.0
    - filelock==3.13.1
    - fonttools==4.51.0
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - furl==2.1.3
    - gmpy2==2.1.2
    - greenlet==3.0.3
    - huggingface-hub==0.23.3
    - hyperlink==21.0.0
    - idna==3.7
    - incremental==22.10.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.4
    - linear-attention-transformer==0.19.1
    - linformer==0.2.3
    - local-attention==1.9.1
    - mamba-ssm==2.0.4
    - markupsafe==2.1.3
    - matplotlib==3.8.4
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.2.1
    - ninja==1.11.1.1
    - numexpr==2.8.7
    - numpy==1.26.4
    - orderedmultidict==1.0.1
    - packaging==23.2
    - pandas==2.2.2
    - pillow==10.3.0
    - pip==24.0
    - ply==3.11
    - product-key-memory==0.2.10
    - propcache==0.2.0
    - psutil==5.9.0
    - pykalman==0.10.1
    - pyparsing==3.0.9
    - pyqt5==5.15.10
    - pyqt5-sip==12.13.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytorch-metric-learning==2.5.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - redo==2.0.4
    - regex==2024.5.15
    - requests==2.32.2
    - safetensors==0.4.3
    - scikit-base==0.12.0
    - scikit-learn==1.6.1
    - scipy==1.15.1
    - setuptools==69.5.1
    - simplejson==3.19.2
    - sip==6.7.12
    - sqlalchemy==2.0.30
    - sympy==1.12
    - threadpoolctl==3.5.0
    - tokenizers==0.19.1
    - tomli==2.0.1
    - torch==2.1.1
    - torch-geometric==2.5.2
    - torchaudio==2.1.1
    - torchcde==0.2.5
    - torchdiffeq==0.2.4
    - torchsde==0.2.6
    - torchvision==0.16.1
    - tornado==6.3.3
    - tqdm==4.66.4
    - trampoline==0.1.2
    - transformers==4.41.2
    - triton==2.1.0
    - twisted==24.3.0
    - typing-extensions==4.11.0
    - unicodedata2==15.1.0
    - urllib3==2.2.1
    - wheel==0.43.0
    - yarl==1.18.0
    - zope-interface==6.4.post2
